### ISSUE TITLE
kono-api - Bug: GET /api/v1/post

### ISSUE THREAD

**Issue by inhibitor1217** [sparcs-kaist/kono#25]
Stacktrace:
```bash
(node:12196) UnhandledPromiseRejectionWarning: Error: "startIndex" is read-only
    at _readOnlyError (/home/ubuntu/kono/kono-api/src/api/v1/post/post.control.js:30:39)
    at _callee$ (/home/ubuntu/kono/kono-api/src/api/v1/post/post.control.js:20:19)
    at tryCatch (/home/ubuntu/kono/kono-api/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/ubuntu/kono/kono-api/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/kono/kono-api/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/ubuntu/kono/kono-api/src/api/v1/post/post.control.js:32:103)
    at _next (/home/ubuntu/kono/kono-api/src/api/v1/post/post.control.js:34:194)
    at /home/ubuntu/kono/kono-api/src/api/v1/post/post.control.js:34:364
    at new Promise (<anonymous>)
    at /home/ubuntu/kono/kono-api/src/api/v1/post/post.control.js:34:97
```

**Comment by inhibitor1217** [comment]
멍청한 실수네요...
`const { ..., start_index: startIndex }`로 선언해놓고 뒤에서 assign `startIndex = 0` 해버림...
